# Generated by Django 6.0.2 on 2026-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_parkingslot_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
