# Generated by Django 6.0.2 on 2026-03-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_parkingslot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
