# Generated by Django 6.0.2 on 2026-04-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_parkingslot_amount_parkingslot_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
